# This SPARQL update query cross-references agricultural crop observation sets
# across different systems and materializes their relationships according to SKOS.

PREFIX eCH-0265: <https://agriculture.ld.admin.ch/eCH-0265/2/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

# 1. EXACT MATCH
INSERT {
  ?s skos:exactMatch ?t .
}
WHERE {
  ?s skos:inScheme ?s_scheme .
  ?t skos:inScheme ?t_scheme .
  FILTER(?s_scheme != ?t_scheme)
  ?s eCH-0265:exactMatch / ^eCH-0265:exactMatch ?t .
};

# 2. BROAD MATCH
INSERT {
  ?s skos:broadMatch ?t .
}
WHERE {
  ?s skos:inScheme ?s_scheme .
  ?t skos:inScheme ?t_scheme .
  FILTER(?s_scheme != ?t_scheme)
  ?s eCH-0265:exactMatch / rdfs:subClassOf+ / ^eCH-0265:exactMatch ?t .
  FILTER NOT EXISTS { 
    ?s eCH-0265:exactMatch / ^skos:inScheme ?t_scheme . 
  }
};

# 3. NARROW MATCH
INSERT {
  ?s skos:narrowMatch ?t .
}
WHERE {
  ?s skos:inScheme ?s_scheme .
  ?t skos:inScheme ?t_scheme .
  FILTER(?s_scheme != ?t_scheme)
  ?s eCH-0265:exactMatch / ^rdfs:subClassOf+ / ^eCH-0265:exactMatch ?t .
  FILTER NOT EXISTS { 
    ?s (eCH-0265:exactMatch|skos:broadMatch) / ^skos:inScheme ?t_scheme .
  }
}
