PREFIX : <https://agriculture.ld.admin.ch/crops/>
PREFIX cube: <https://cube.link/>

SELECT DISTINCT ?CultivationType ?System
FROM <https://lindas.admin.ch/foag/crops>
WHERE {
  ?System cube:observationSet / cube:observation / (:cultivationType|:cultivationGroup|:cultivationGroup|:cultivationCategory|:cultivationSubCategory) ?CultivationType .
}
