PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

INSERT {
  ?A owl:disjointWith ?B .
}
WHERE {
  [] a owl:AllDisjointClasses ;
     owl:members ?members .    
  ?members rdf:rest*/rdf:first ?A .    
  ?members rdf:rest*/rdf:first ?B .
  FILTER (?A != ?B)
}