project:
  output-dir: ../build/docs/
  type: website
  render:
    - de/index.qmd

website:
  repo-url: https://github.com/blw-ofag-ufag/eCH-0265
  repo-subdir: docs
  repo-actions: [source, issue]
  favicon: assets/favicon.svg
  navbar:
    right:
      - icon: github
        href: https://github.com/blw-ofag-ufag/eCH-0265
      - icon: envelope
        href: mailto:agridata.ch@blw.admin.ch

bibliography: references.bib

format:
  html:
    toc: true
    number-sections: true
  gfm: 
    toc: true
    number-sections: true
  docx:
    toc: true
    reference-doc: https://s.zazuko.com/MHXTkQ
    link-citations: true
  typst:
    number-sections: true