project:
  output-dir: ../build/docs/
  type: website
  render:
    - de/index.qmd

website:
  title: eCH-0265 Version 2.0.0 (Working Draft)
  repo-url: https://github.com/blw-ofag-ufag/eCH-0265
  repo-subdir: docs
  repo-actions: [source, issue]
  favicon: assets/favicon.svg
  navbar:
    background: dark
    right:
      - icon: github
        href: https://github.com/blw-ofag-ufag/eCH-0265
      - icon: envelope
        href: mailto:agridata.ch@blw.admin.ch
  announcement:
    icon: info-circle
    dismissable: true
    content: Diese Seite beinhaltet einen *Working Draft* und kann sich dadurch laufend verändern. Für eine aktuelle Version, besuchen Sie [ech.ch](https://ech.ch/de/ech/ech-0265/).
    type: warning

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    number-sections: true
    syntax-definitions:
     - assets/sparql.xml
     - assets/turtle.xml
  gfm: 
    toc: true
    toc-depth: 2
    number-sections: true
  docx:
    toc: true
    toc-depth: 2
    number-sections: true
    reference-doc: https://s.zazuko.com/MHXTkQ
    link-citations: true
  typst:
    toc: true
    toc-depth: 3
    number-sections: true
    section-numbering: 1.1.1
    mainfont: Nimbus Sans
    fontsize: 12pt
    margin:
      x: 2.5cm
      y: 3.5cm
    include-in-header: assets/typst-header.typ
    include-before-body: assets/typst-before-body.typ
    syntax-definitions:
     - assets/sparql.xml
     - assets/turtle.xml
    citeproc: true